blogger_user:
    resource: "@BloggerUserBundle/Controller/"
    type:     annotation
    prefix:   /

blogger_blog:
    resource: "@BloggerBlogBundle/Controller/"
    type:     annotation
    prefix:   /

