security:
    encoders:
        Blogger\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
                entity: { class: BloggerUserBundle:User }

    firewalls:
        admin_area:
                pattern: ^/post/admin
                http_basic: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }