services:
        sonata.admin.blog:
                class: Blogger\BlogBundle\Admin\BlogAdmin
                tags:
                        - { name: sonata.admin, manager_type: orm, group: "Content", label: "Blog" }
                arguments:
                        - ~
                        - Blogger\BlogBundle\Entity\Blog
                        - BloggerBlogBundle:BlogAdmin
                calls:
                        - [ setTranslationDomain, [BloggerBlogBundle]]