<?php

namespace Blogger\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
  /**
   * Grabs all comments for blog with given blogid
   */
  public function getCommentsForBlog($blogId, $approved = true)
  {
    $qb = $this->createQueryBuilder('c')
      ->select('c')
      ->where('c.blog = :blog_id')
      ->setParameter('blog_id', $blogId)
      ->addOrderBy('c.created');

    if(false === is_null($approved))
      {
        $qb->andWhere('c.approved = :approved')
          ->setParameter('approved', $approved);
      }

    return $qb->getQuery()->getResult();
  }

  public function getLatestComments($limit = 10)
  {
    $qb = $this->createQueryBuilder('c')
      ->select('c')
      ->addOrderBy('c.id', 'DESC');

    if(false === is_null($limit))
      {
        $qb->setMaxResults($limit);
      }

    return $qb->getQuery()->getResult();
  }
}
